"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://sparq.ulb.be/
  name = sparqulb

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.WikibaseFamily):  # noqa: D101

    name = 'sparqulb'
    langs = {
        'en': 'sparq.ulb.be',
    }

    def scriptpath(self, code):
        return {
            'en': '/w',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
        }[code]
    
    def calendarmodel(self, code):
        """Default calendar model for WbTime datatype."""
        return 'http://www.wikidata.org/entity/Q1985727'
